import { NextResponse } from 'next/server';

export async function GET(request: Request) {
  const host = request.headers.get('host') || 'auditsentinel.akhzafachrozy.my.id';
  const protocol = host.includes('localhost') ? 'http' : 'https';
  const serverUrl = `${protocol}://${host}`;

  const bashScript = `#!/usr/bin/env bash
# ==============================================================================
# Sentinel Linux Security Audit Agent Installer
# Auto-generated by Sentinel Dashboard (${serverUrl})
# ==============================================================================

set -eo pipefail

echo -e "\\033[1;33m"
cat << 'EOF'
  ___ ___ _  _ _____ ___ _  _ ___ _    
 / __| __| \\| |_   _|_ _| \\| | __| |   
 \\__ \\ _|| .  | | |  | || .  | _|| |__ 
 |___/___|_|\\_| |_| |___|_|\\_|___|____|
 Linux Security Audit & Hardening Agent
EOF
echo -e "\\033[0m"

if [ "$EUID" -ne 0 ]; then
  echo -e "\\033[0;31m[ERROR] Please run installer as root or with sudo.\\033[0m"
  exit 1
fi

INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/sentinel"
BIN_TARGET="$INSTALL_DIR/sentinel"

mkdir -p "$CONFIG_DIR" "$INSTALL_DIR" /var/lib/sentinel /var/backups/sentinel

echo "[1/3] Downloading latest Sentinel Agent script..."
curl -fsSL "${serverUrl}/sentinel-agent.sh" -o "$BIN_TARGET" || \\
curl -fsSL "https://raw.githubusercontent.com/sentinel-sec/agent/main/sentinel-agent.sh" -o "$BIN_TARGET" 2>/dev/null || true

if [ ! -s "$BIN_TARGET" ]; then
  echo "[1/3] Fallback: Writing embedded agent executable..."
  cat << 'AGENT_EOF' > "$BIN_TARGET"
#!/usr/bin/env bash
echo "Sentinel Linux Audit Agent v1.4.2"
# Download complete agent script
curl -fsSL "${serverUrl}/api/agent/agent.sh" -o /usr/local/bin/sentinel
chmod +x /usr/local/bin/sentinel
exec /usr/local/bin/sentinel "$@"
AGENT_EOF
fi

chmod +x "$BIN_TARGET"
echo -e "\\033[0;32m[2/3] Sentinel binary installed to $BIN_TARGET\\033[0m"

echo "[3/3] Setting up configuration template..."
cat << EOF > "$CONFIG_DIR/config.json"
{
  "server": "${serverUrl}",
  "token": "sentinel_auto_$(date +%s)",
  "server_id": "$(hostname)",
  "registered_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF
chmod 600 "$CONFIG_DIR/config.json"

echo -e "\\033[1;32m"
echo "=========================================================="
echo " Sentinel Agent Installed Successfully! "
echo "=========================================================="
echo -e "\\033[0m"
echo "To connect to your dashboard, run:"
echo -e "  \\033[1;36msentinel register --token <YOUR_AGENT_TOKEN> --server ${serverUrl}\\033[0m"
echo ""
echo "To execute your first security audit:"
echo -e "  \\033[1;36msentinel audit\\033[0m"
echo ""
`;

  return new NextResponse(bashScript, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
    },
  });
}
